apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devops-sample
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-devops-sample
  template:
    metadata:
      labels:
        app: java-devops-sample
    spec:
      containers:
        - name: java-devops-sample
          image: 400714277648.dkr.ecr.ap-south-1.amazonaws.com/java-devops-sample:c3c16272e3b0ff86c23bdb7aafb70ec7e75d2e2c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
